/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Figuras;

/**
 *
 * @author Alejandro Bernal
 */
public class VentanaPrincipalFiguras extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipalFiguras
     */
    public VentanaPrincipalFiguras() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtcradio = new javax.swing.JTextField();
        txtcarea = new javax.swing.JTextField();
        txtcperimetro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnarea = new javax.swing.JButton();
        btnperimetro = new javax.swing.JButton();
        btnborrar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btncuarea = new javax.swing.JButton();
        btncuperimetro = new javax.swing.JButton();
        btncuborrar = new javax.swing.JButton();
        txtculado = new javax.swing.JTextField();
        txtcuarea = new javax.swing.JTextField();
        txtcuperimetro = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnrarea = new javax.swing.JButton();
        btnrperimetro = new javax.swing.JButton();
        btnrborrar = new javax.swing.JButton();
        txtrbase = new javax.swing.JTextField();
        txtraltura = new javax.swing.JTextField();
        txtrarea = new javax.swing.JTextField();
        txtrperimetro = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txttbase = new javax.swing.JTextField();
        txttaltura = new javax.swing.JTextField();
        txttarea = new javax.swing.JTextField();
        txttperimetro = new javax.swing.JTextField();
        txtthipotenusa = new javax.swing.JTextField();
        btntarea = new javax.swing.JButton();
        btntperimetro = new javax.swing.JButton();
        btnthipotenusa = new javax.swing.JButton();
        btntborrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Radio");

        jLabel2.setText("Area");

        jLabel3.setText("Perimetro");

        txtcradio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcradioActionPerformed(evt);
            }
        });

        jLabel4.setText("Circulo");

        btnarea.setText("Calcular Area");
        btnarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnareaActionPerformed(evt);
            }
        });

        btnperimetro.setText("Calcular Perimetro");
        btnperimetro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnperimetroActionPerformed(evt);
            }
        });

        btnborrar.setText("Borrar");
        btnborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnborrarActionPerformed(evt);
            }
        });

        jLabel5.setText("Cuadrado");

        jLabel6.setText("Lado");

        jLabel7.setText("Area");

        jLabel8.setText("Perimetro");

        btncuarea.setText("Calcular Area");
        btncuarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncuareaActionPerformed(evt);
            }
        });

        btncuperimetro.setText("Calcular Perimetro");
        btncuperimetro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncuperimetroActionPerformed(evt);
            }
        });

        btncuborrar.setText("Borrar");
        btncuborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncuborrarActionPerformed(evt);
            }
        });

        jLabel9.setText("Rectangulo");

        jLabel10.setText("Base");

        jLabel11.setText("Altura");

        jLabel12.setText("Area");

        jLabel13.setText("Perimetro");

        btnrarea.setText("Calcular Area");
        btnrarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrareaActionPerformed(evt);
            }
        });

        btnrperimetro.setText("Calcular Perimetro");
        btnrperimetro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrperimetroActionPerformed(evt);
            }
        });

        btnrborrar.setText("Borrar");
        btnrborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrborrarActionPerformed(evt);
            }
        });

        jLabel14.setText("Triangulo Rectangulo");

        jLabel15.setText("Base");

        jLabel16.setText("Altura");

        jLabel17.setText("Area");

        jLabel18.setText("Perimetro");

        jLabel19.setText("Hipotenusa");

        btntarea.setText("Calcular Area");
        btntarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntareaActionPerformed(evt);
            }
        });

        btntperimetro.setText("Calcular Perimetro");
        btntperimetro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntperimetroActionPerformed(evt);
            }
        });

        btnthipotenusa.setText("Calcular Hipotenusa");
        btnthipotenusa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthipotenusaActionPerformed(evt);
            }
        });

        btntborrar.setText("Borrar");
        btntborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntborrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtcperimetro, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtcradio, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtcarea, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(btnperimetro)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnborrar))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnarea)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnrarea, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtrbase)
                                .addComponent(txtraltura)
                                .addComponent(txtrarea)
                                .addComponent(txtrperimetro, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnrperimetro, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnrborrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(btncuarea)
                                                .addGap(53, 53, 53)
                                                .addComponent(btncuperimetro))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txttperimetro, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(txttarea, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(txttaltura, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(txtthipotenusa, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(txttbase, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(10, 10, 10))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtcuarea, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                            .addComponent(txtculado, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtcuperimetro, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addComponent(btncuborrar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                                        .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnthipotenusa, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btntborrar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btntarea, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btntperimetro, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(188, 188, 188))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtcradio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtculado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtcarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtcuarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtcperimetro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtcuperimetro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnarea)
                    .addComponent(btnperimetro)
                    .addComponent(btnborrar)
                    .addComponent(btncuarea)
                    .addComponent(btncuperimetro)
                    .addComponent(btncuborrar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtrbase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(txttbase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtraltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(txttaltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtrarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(txttarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtrperimetro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(txttperimetro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnrarea)
                    .addComponent(btnrperimetro)
                    .addComponent(btnrborrar)
                    .addComponent(jLabel19)
                    .addComponent(txtthipotenusa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btntarea)
                    .addComponent(btntperimetro))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnthipotenusa)
                    .addComponent(btntborrar))
                .addContainerGap(105, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnareaActionPerformed
        // TODO add your handling code here:
        int radio = Integer.parseInt(txtcradio.getText());
        Circulo figura1 = new Circulo(radio);
        double area;
        area=figura1.calcularArea();
        txtcarea.setText(String.valueOf(area));
    }//GEN-LAST:event_btnareaActionPerformed

    private void btnborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnborrarActionPerformed
        // TODO add your handling code here:
        txtcarea.setText("");
        txtcperimetro.setText("");
        txtcradio.setText("");
        
    }//GEN-LAST:event_btnborrarActionPerformed

    private void btnperimetroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnperimetroActionPerformed
        int radio = Integer.parseInt(txtcradio.getText());
        Circulo figura1 = new Circulo(radio);
        double perimetro;
        perimetro=figura1.calcularPerimetro();
        txtcperimetro.setText(String.valueOf(perimetro));
        // TODO add your handling code here:
    }//GEN-LAST:event_btnperimetroActionPerformed

    private void txtcradioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcradioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcradioActionPerformed

    private void btncuareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncuareaActionPerformed
        int lado= Integer.parseInt(txtculado.getText());
        Cuadrado figura3 = new Cuadrado(lado);
        double area;
        area=figura3.calcularArea();
        txtcuarea.setText(String.valueOf(area));        // TODO add your handling code here:
    }//GEN-LAST:event_btncuareaActionPerformed

    private void btncuperimetroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncuperimetroActionPerformed
        // TODO add your handling code here:
        int lado= Integer.parseInt(txtculado.getText());
        Cuadrado figura3 = new Cuadrado(lado);
        double perimetro;
        perimetro=figura3.calcularPerimetro();
        txtcuperimetro.setText(String.valueOf(perimetro));
    }//GEN-LAST:event_btncuperimetroActionPerformed

    private void btncuborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncuborrarActionPerformed
        // TODO add your handling code here:
        txtcuarea.setText("");
        txtcuperimetro.setText("");
        txtculado.setText("");
    }//GEN-LAST:event_btncuborrarActionPerformed

    private void btnrareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrareaActionPerformed
        // TODO add your handling code here:
        int base_rectangulo = Integer.parseInt(txtrbase.getText());
        int altura_rectangulo = Integer.parseInt(txtraltura.getText());
        Rectangulo figura2 = new Rectangulo(base_rectangulo,altura_rectangulo);
        double area;
        area=figura2.calcularArea();
        txtrarea.setText(String.valueOf(area));
    }//GEN-LAST:event_btnrareaActionPerformed

    private void btnrperimetroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrperimetroActionPerformed
        // TODO add your handling code here:
        int base_rectangulo = Integer.parseInt(txtrbase.getText());
        int altura_rectangulo = Integer.parseInt(txtraltura.getText());
        Rectangulo figura2 = new Rectangulo(base_rectangulo,altura_rectangulo);
        double perimetro;
        perimetro=figura2.calcularPerimetro();
        txtrperimetro.setText(String.valueOf(perimetro));
    }//GEN-LAST:event_btnrperimetroActionPerformed

    private void btnrborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrborrarActionPerformed
        // TODO add your handling code here:
        txtrarea.setText("");
        txtrperimetro.setText("");
        txtraltura.setText("");
        txtrbase.setText("");
    }//GEN-LAST:event_btnrborrarActionPerformed

    private void btntareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntareaActionPerformed
        // TODO add your handling code here:
        int base_TrianguloRectangulo = Integer.parseInt(txttbase.getText());
        int altura_TrianguloRectangulo = Integer.parseInt(txttaltura.getText());
        TrianguloRectangulo figura4 = new TrianguloRectangulo(base_TrianguloRectangulo,altura_TrianguloRectangulo);
        double area;
        area=figura4.calcularArea();
        txttarea.setText(String.valueOf(area));
    }//GEN-LAST:event_btntareaActionPerformed

    private void btntperimetroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntperimetroActionPerformed
        // TODO add your handling code here:
        int base_TrianguloRectangulo = Integer.parseInt(txttbase.getText());
        int altura_TrianguloRectangulo = Integer.parseInt(txttaltura.getText());
        TrianguloRectangulo figura4 = new TrianguloRectangulo(base_TrianguloRectangulo,altura_TrianguloRectangulo);
        double perimetro;
        perimetro=figura4.calcularPerimetro();
        txttperimetro.setText(String.valueOf(perimetro));
    }//GEN-LAST:event_btntperimetroActionPerformed

    private void btnthipotenusaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthipotenusaActionPerformed
        // TODO add your handling code here:
        int base_TrianguloRectangulo = Integer.parseInt(txttbase.getText());
        int altura_TrianguloRectangulo = Integer.parseInt(txttaltura.getText());
        TrianguloRectangulo figura4 = new TrianguloRectangulo(base_TrianguloRectangulo,altura_TrianguloRectangulo);
        double hipotenusa;
        hipotenusa=figura4.calcularHipotenusa();
        txtthipotenusa.setText(String.valueOf(hipotenusa));
    }//GEN-LAST:event_btnthipotenusaActionPerformed

    private void btntborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntborrarActionPerformed
        // TODO add your handling code here:
        txttarea.setText("");
        txttperimetro.setText("");
        txttaltura.setText("");
        txttbase.setText("");
        txtthipotenusa.setText("");
    }//GEN-LAST:event_btntborrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalFiguras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalFiguras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalFiguras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalFiguras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipalFiguras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnarea;
    private javax.swing.JButton btnborrar;
    private javax.swing.JButton btncuarea;
    private javax.swing.JButton btncuborrar;
    private javax.swing.JButton btncuperimetro;
    private javax.swing.JButton btnperimetro;
    private javax.swing.JButton btnrarea;
    private javax.swing.JButton btnrborrar;
    private javax.swing.JButton btnrperimetro;
    private javax.swing.JButton btntarea;
    private javax.swing.JButton btntborrar;
    private javax.swing.JButton btnthipotenusa;
    private javax.swing.JButton btntperimetro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtcarea;
    private javax.swing.JTextField txtcperimetro;
    private javax.swing.JTextField txtcradio;
    private javax.swing.JTextField txtcuarea;
    private javax.swing.JTextField txtculado;
    private javax.swing.JTextField txtcuperimetro;
    private javax.swing.JTextField txtraltura;
    private javax.swing.JTextField txtrarea;
    private javax.swing.JTextField txtrbase;
    private javax.swing.JTextField txtrperimetro;
    private javax.swing.JTextField txttaltura;
    private javax.swing.JTextField txttarea;
    private javax.swing.JTextField txttbase;
    private javax.swing.JTextField txtthipotenusa;
    private javax.swing.JTextField txttperimetro;
    // End of variables declaration//GEN-END:variables
}
